//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table2
    {
        public int S_no { get; set; }
        public string cornflakes { get; set; }
        public string raisins { get; set; }
        public string almond { get; set; }
        public string DriedFruits { get; set; }
        public string Peanuts { get; set; }
    }
}
